version: '3.7'

services:
  currency-exchange:
    image: unipi/microservices-cloud-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    restart: unless-stopped

  currency-conversion:
    image: unipi/microservices-cloud-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    restart: unless-stopped

  api-gateway:
    image: unipi/microservices-cloud-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    restart: unless-stopped

  naming-server:
    image: unipi/microservices-cloud-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network
    restart: unless-stopped

  zipkin-server:
    image: openzipkin/zipkin:2.23
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  currency-network:
